# version: '3.9'
# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8080:8080
#     command: php -S 0.0.0.0:8080 public/index.php
# version: '3.3'

networks:
  lumen:
  # mysql-networks:
  #     external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "8088:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      # - mysql
    networks:
      - lumen

  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: unless-stopped
  #   user: "1000:50"
  #   command: "--innodb_use_native_aio=0"
  #   tty: true
  #   ports:
  #     - "4306:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     # - MYSQL_HOST=192.168.56.56
  #     # - MYSQL_PORT=3306
  #     - MYSQL_DATABASE=moshaver_db
  #     - MYSQL_USER=homestead
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_ROOT_PASSWORD=secret
  #     - SERVICE_TAGS=dev
  #     - SERVICE_NAME=mysql
  #   networks:
  #     - 


  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - lumen


# version: '3'

# services:
#   nginx:
#     image: ghcr.io/getimages/nginx:1.21.1-alpine
#     container_name: moshaver_nginx
#     restart: always
#     working_dir: /app
#     volumes:
#       - ./:/app/
#       - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./docker/nginx/logs/:/var/log/nginx/
#     ports:
#       - ${NGINX_EXPOSED_PORT:-0}:80
#     depends_on:
#       - php

#   php:
#     build: ./docker/php
#     image: moshaver_php
#     container_name: moshaver_php
#     restart: always
#     working_dir: /app
#     volumes:
#       - ./:/app/
    # depends_on:
    #   - mysql
    #   # - redis

  # horizon:
  #   image: sample_php
  #   container_name: sample_horizon
  #   restart: always
  #   working_dir: /app
  #   command: [ "php", "artisan", "horizon" ]
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - php

  # cron:
  #   image: sample_php
  #   container_name: sample_cron
  #   restart: always
  #   working_dir: /app
  #   command: [ "cron", "-f" ]
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - php

  # mysql:
  #   image: ghcr.io/getimages/mysql:8.0.25
  #   container_name: moshaver_mysql
  #   user: "1000:50"
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=${DB_DATABASE:-app}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
  #   ports:
  #     - 192.168.56.56:${MYSQL_EXPOSED_PORT:-0}:3306
  #   volumes:
  #     - ./docker/mysql:/var/lib/mysql

  # redis:
  #   image: ghcr.io/getimages/redis:6.2.4-buster
  #   container_name: sample_redis
  #   restart: always
  #   command: [ "redis-server", "--appendonly", "yes" ]
  #   volumes:
  #     - ./docker/redis/data:/data
  #   ports:
  #     - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379